# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Installer(object):
    def setupUi(self, Installer):
        Installer.setObjectName("Installer")
        Installer.setWindowModality(QtCore.Qt.NonModal)
        Installer.setEnabled(True)
        Installer.resize(1152, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Installer.sizePolicy().hasHeightForWidth())
        Installer.setSizePolicy(sizePolicy)
        Installer.setFocusPolicy(QtCore.Qt.TabFocus)
        Installer.setStatusTip("")
        Installer.setAutoFillBackground(True)
        Installer.setSizeGripEnabled(True)
        Installer.setModal(False)
        Installer.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        Installer.setOptions(QtWidgets.QWizard.NoCancelButton)
        self.home_page = QtWidgets.QWizardPage()
        self.home_page.setAutoFillBackground(False)
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        Installer.addPage(self.home_page)
        self.connect_page = QtWidgets.QWizardPage()
        self.connect_page.setObjectName("connect_page")
        self.connect_server_conf = QtWidgets.QGroupBox(self.connect_page)
        self.connect_server_conf.setGeometry(QtCore.QRect(280, 90, 581, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_server_conf.sizePolicy().hasHeightForWidth())
        self.connect_server_conf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.connect_server_conf.setFont(font)
        self.connect_server_conf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.connect_server_conf.setInputMethodHints(QtCore.Qt.ImhNone)
        self.connect_server_conf.setFlat(False)
        self.connect_server_conf.setCheckable(False)
        self.connect_server_conf.setObjectName("connect_server_conf")
        self.label_25 = QtWidgets.QLabel(self.connect_server_conf)
        self.label_25.setGeometry(QtCore.QRect(20, 40, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.location = QtWidgets.QComboBox(self.connect_server_conf)
        self.location.setGeometry(QtCore.QRect(270, 40, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.location.setFont(font)
        self.location.setObjectName("location")
        self.location.addItem("")
        self.location.addItem("")
        self.label_28 = QtWidgets.QLabel(self.connect_server_conf)
        self.label_28.setGeometry(QtCore.QRect(10, 230, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_27 = QtWidgets.QLabel(self.connect_server_conf)
        self.label_27.setGeometry(QtCore.QRect(10, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.username = QtWidgets.QLineEdit(self.connect_server_conf)
        self.username.setGeometry(QtCore.QRect(170, 170, 321, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setMinimumSize(QtCore.QSize(321, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setFrame(True)
        self.username.setObjectName("username")
        self.user_password = QtWidgets.QLineEdit(self.connect_server_conf)
        self.user_password.setGeometry(QtCore.QRect(170, 230, 321, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_password.sizePolicy().hasHeightForWidth())
        self.user_password.setSizePolicy(sizePolicy)
        self.user_password.setMinimumSize(QtCore.QSize(321, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.user_password.setFont(font)
        self.user_password.setFrame(True)
        self.user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password.setObjectName("user_password")
        self.button_ssh_control = QtWidgets.QPushButton(self.connect_server_conf)
        self.button_ssh_control.setEnabled(True)
        self.button_ssh_control.setGeometry(QtCore.QRect(380, 300, 111, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ssh_control.sizePolicy().hasHeightForWidth())
        self.button_ssh_control.setSizePolicy(sizePolicy)
        self.button_ssh_control.setMinimumSize(QtCore.QSize(111, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.button_ssh_control.setFont(font)
        self.button_ssh_control.setCheckable(True)
        self.button_ssh_control.setChecked(False)
        self.button_ssh_control.setObjectName("button_ssh_control")
        self.server_host = QtWidgets.QLineEdit(self.connect_server_conf)
        self.server_host.setGeometry(QtCore.QRect(170, 110, 321, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_host.sizePolicy().hasHeightForWidth())
        self.server_host.setSizePolicy(sizePolicy)
        self.server_host.setMinimumSize(QtCore.QSize(321, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.server_host.setFont(font)
        self.server_host.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.server_host.setFrame(True)
        self.server_host.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.server_host.setObjectName("server_host")
        self.label_14 = QtWidgets.QLabel(self.connect_server_conf)
        self.label_14.setGeometry(QtCore.QRect(10, 170, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        Installer.addPage(self.connect_page)
        self.lider_conf_page = QtWidgets.QWizardPage()
        self.lider_conf_page.setObjectName("lider_conf_page")
        self.textBrowser_43 = QtWidgets.QTextBrowser(self.lider_conf_page)
        self.textBrowser_43.setGeometry(QtCore.QRect(380, 10, 321, 31))
        self.textBrowser_43.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_43.setObjectName("textBrowser_43")
        self.ldap_server_conf = QtWidgets.QGroupBox(self.lider_conf_page)
        self.ldap_server_conf.setGeometry(QtCore.QRect(50, 70, 490, 411))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ldap_server_conf.setFont(font)
        self.ldap_server_conf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ldap_server_conf.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ldap_server_conf.setFlat(False)
        self.ldap_server_conf.setCheckable(False)
        self.ldap_server_conf.setObjectName("ldap_server_conf")
        self.l_base_dn = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.l_base_dn.setGeometry(QtCore.QRect(260, 170, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_base_dn.sizePolicy().hasHeightForWidth())
        self.l_base_dn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.l_base_dn.setFont(font)
        self.l_base_dn.setObjectName("l_base_dn")
        self.l_admin_pwd = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.l_admin_pwd.setGeometry(QtCore.QRect(260, 130, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_admin_pwd.sizePolicy().hasHeightForWidth())
        self.l_admin_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.l_admin_pwd.setFont(font)
        self.l_admin_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.l_admin_pwd.setObjectName("l_admin_pwd")
        self.ldap_admin_cn = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.ldap_admin_cn.setGeometry(QtCore.QRect(260, 90, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ldap_admin_cn.sizePolicy().hasHeightForWidth())
        self.ldap_admin_cn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ldap_admin_cn.setFont(font)
        self.ldap_admin_cn.setObjectName("ldap_admin_cn")
        self.label_2 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_2.setGeometry(QtCore.QRect(10, 55, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_3.setGeometry(QtCore.QRect(10, 95, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_4.setGeometry(QtCore.QRect(10, 135, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_5.setGeometry(QtCore.QRect(10, 175, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lider_console_user = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.lider_console_user.setGeometry(QtCore.QRect(260, 330, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lider_console_user.sizePolicy().hasHeightForWidth())
        self.lider_console_user.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lider_console_user.setFont(font)
        self.lider_console_user.setObjectName("lider_console_user")
        self.l_org_name = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.l_org_name.setGeometry(QtCore.QRect(260, 210, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.l_org_name.setFont(font)
        self.l_org_name.setObjectName("l_org_name")
        self.label_6 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_6.setGeometry(QtCore.QRect(10, 295, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_7.setGeometry(QtCore.QRect(10, 255, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.l_config_admin_dn = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.l_config_admin_dn.setGeometry(QtCore.QRect(260, 250, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_config_admin_dn.sizePolicy().hasHeightForWidth())
        self.l_config_admin_dn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.l_config_admin_dn.setFont(font)
        self.l_config_admin_dn.setObjectName("l_config_admin_dn")
        self.label_8 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_8.setGeometry(QtCore.QRect(10, 335, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_9.setGeometry(QtCore.QRect(10, 215, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.l_config_pwd = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.l_config_pwd.setGeometry(QtCore.QRect(260, 290, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_config_pwd.sizePolicy().hasHeightForWidth())
        self.l_config_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.l_config_pwd.setFont(font)
        self.l_config_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.l_config_pwd.setObjectName("l_config_pwd")
        self.label_10 = QtWidgets.QLabel(self.ldap_server_conf)
        self.label_10.setGeometry(QtCore.QRect(10, 375, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lider_console_user_pwd = QtWidgets.QLineEdit(self.ldap_server_conf)
        self.lider_console_user_pwd.setGeometry(QtCore.QRect(260, 370, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lider_console_user_pwd.sizePolicy().hasHeightForWidth())
        self.lider_console_user_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lider_console_user_pwd.setFont(font)
        self.lider_console_user_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lider_console_user_pwd.setObjectName("lider_console_user_pwd")
        self.ldap_status = QtWidgets.QComboBox(self.ldap_server_conf)
        self.ldap_status.setGeometry(QtCore.QRect(260, 55, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ldap_status.setFont(font)
        self.ldap_status.setObjectName("ldap_status")
        self.ldap_status.addItem("")
        self.ldap_status.addItem("")
        self.ldap_install = QtWidgets.QCheckBox(self.ldap_server_conf)
        self.ldap_install.setGeometry(QtCore.QRect(10, 25, 87, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ldap_install.setFont(font)
        self.ldap_install.setObjectName("ldap_install")
        self.database_server_conf = QtWidgets.QGroupBox(self.lider_conf_page)
        self.database_server_conf.setGeometry(QtCore.QRect(50, 510, 490, 201))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.database_server_conf.setFont(font)
        self.database_server_conf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.database_server_conf.setInputMethodHints(QtCore.Qt.ImhNone)
        self.database_server_conf.setFlat(False)
        self.database_server_conf.setCheckable(False)
        self.database_server_conf.setObjectName("database_server_conf")
        self.label_20 = QtWidgets.QLabel(self.database_server_conf)
        self.label_20.setGeometry(QtCore.QRect(10, 170, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.db_username = QtWidgets.QLineEdit(self.database_server_conf)
        self.db_username.setGeometry(QtCore.QRect(260, 125, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_username.sizePolicy().hasHeightForWidth())
        self.db_username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.db_username.setFont(font)
        self.db_username.setObjectName("db_username")
        self.label_19 = QtWidgets.QLabel(self.database_server_conf)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.db_password = QtWidgets.QLineEdit(self.database_server_conf)
        self.db_password.setGeometry(QtCore.QRect(260, 165, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_password.sizePolicy().hasHeightForWidth())
        self.db_password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.db_password.setFont(font)
        self.db_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.db_password.setObjectName("db_password")
        self.label_18 = QtWidgets.QLabel(self.database_server_conf)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.database_server_conf)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.db_server = QtWidgets.QLineEdit(self.database_server_conf)
        self.db_server.setGeometry(QtCore.QRect(260, 45, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_server.sizePolicy().hasHeightForWidth())
        self.db_server.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.db_server.setFont(font)
        self.db_server.setObjectName("db_server")
        self.db_name = QtWidgets.QLineEdit(self.database_server_conf)
        self.db_name.setGeometry(QtCore.QRect(260, 85, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_name.sizePolicy().hasHeightForWidth())
        self.db_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.db_name.setFont(font)
        self.db_name.setObjectName("db_name")
        self.db_install = QtWidgets.QCheckBox(self.database_server_conf)
        self.db_install.setGeometry(QtCore.QRect(10, 25, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.db_install.setFont(font)
        self.db_install.setObjectName("db_install")
        self.file_server_conf = QtWidgets.QGroupBox(self.lider_conf_page)
        self.file_server_conf.setGeometry(QtCore.QRect(600, 410, 490, 301))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.file_server_conf.setFont(font)
        self.file_server_conf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.file_server_conf.setInputMethodHints(QtCore.Qt.ImhNone)
        self.file_server_conf.setFlat(False)
        self.file_server_conf.setCheckable(False)
        self.file_server_conf.setObjectName("file_server_conf")
        self.fs_username = QtWidgets.QLineEdit(self.file_server_conf)
        self.fs_username.setGeometry(QtCore.QRect(240, 85, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_username.sizePolicy().hasHeightForWidth())
        self.fs_username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fs_username.setFont(font)
        self.fs_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fs_username.setObjectName("fs_username")
        self.fs_plugin_path = QtWidgets.QLineEdit(self.file_server_conf)
        self.fs_plugin_path.setGeometry(QtCore.QRect(240, 165, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_plugin_path.sizePolicy().hasHeightForWidth())
        self.fs_plugin_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fs_plugin_path.setFont(font)
        self.fs_plugin_path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fs_plugin_path.setObjectName("fs_plugin_path")
        self.fs_username_pwd = QtWidgets.QLineEdit(self.file_server_conf)
        self.fs_username_pwd.setGeometry(QtCore.QRect(240, 125, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_username_pwd.sizePolicy().hasHeightForWidth())
        self.fs_username_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fs_username_pwd.setFont(font)
        self.fs_username_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.fs_username_pwd.setObjectName("fs_username_pwd")
        self.label_21 = QtWidgets.QLabel(self.file_server_conf)
        self.label_21.setGeometry(QtCore.QRect(10, 170, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.file_server_conf)
        self.label_23.setGeometry(QtCore.QRect(10, 90, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.file_server_conf)
        self.label_24.setGeometry(QtCore.QRect(10, 130, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_22 = QtWidgets.QLabel(self.file_server_conf)
        self.label_22.setGeometry(QtCore.QRect(10, 210, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_26 = QtWidgets.QLabel(self.file_server_conf)
        self.label_26.setGeometry(QtCore.QRect(10, 250, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.fs_agent_files_path = QtWidgets.QLineEdit(self.file_server_conf)
        self.fs_agent_files_path.setGeometry(QtCore.QRect(240, 200, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_agent_files_path.sizePolicy().hasHeightForWidth())
        self.fs_agent_files_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fs_agent_files_path.setFont(font)
        self.fs_agent_files_path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fs_agent_files_path.setObjectName("fs_agent_files_path")
        self.fs_agreement_path = QtWidgets.QLineEdit(self.file_server_conf)
        self.fs_agreement_path.setGeometry(QtCore.QRect(240, 245, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_agreement_path.sizePolicy().hasHeightForWidth())
        self.fs_agreement_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fs_agreement_path.setFont(font)
        self.fs_agreement_path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fs_agreement_path.setObjectName("fs_agreement_path")
        self.label_32 = QtWidgets.QLabel(self.file_server_conf)
        self.label_32.setGeometry(QtCore.QRect(10, 52, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.file_server = QtWidgets.QLineEdit(self.file_server_conf)
        self.file_server.setGeometry(QtCore.QRect(240, 51, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_server.sizePolicy().hasHeightForWidth())
        self.file_server.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.file_server.setFont(font)
        self.file_server.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.file_server.setObjectName("file_server")
        self.lider_install = QtWidgets.QCheckBox(self.file_server_conf)
        self.lider_install.setGeometry(QtCore.QRect(10, 25, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lider_install.setFont(font)
        self.lider_install.setObjectName("lider_install")
        self.save_button = QtWidgets.QPushButton(self.lider_conf_page)
        self.save_button.setGeometry(QtCore.QRect(1010, 740, 83, 24))
        self.save_button.setStyleSheet("")
        self.save_button.setObjectName("save_button")
        self.ejabberd_server_conf = QtWidgets.QGroupBox(self.lider_conf_page)
        self.ejabberd_server_conf.setGeometry(QtCore.QRect(600, 70, 490, 311))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ejabberd_server_conf.setFont(font)
        self.ejabberd_server_conf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ejabberd_server_conf.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ejabberd_server_conf.setFlat(False)
        self.ejabberd_server_conf.setCheckable(False)
        self.ejabberd_server_conf.setObjectName("ejabberd_server_conf")
        self.e_service_name = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.e_service_name.setGeometry(QtCore.QRect(230, 51, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_service_name.sizePolicy().hasHeightForWidth())
        self.e_service_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.e_service_name.setFont(font)
        self.e_service_name.setObjectName("e_service_name")
        self.e_username = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.e_username.setGeometry(QtCore.QRect(230, 91, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_username.sizePolicy().hasHeightForWidth())
        self.e_username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.e_username.setFont(font)
        self.e_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.e_username.setObjectName("e_username")
        self.e_user_pwd = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.e_user_pwd.setGeometry(QtCore.QRect(230, 131, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_user_pwd.sizePolicy().hasHeightForWidth())
        self.e_user_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.e_user_pwd.setFont(font)
        self.e_user_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.e_user_pwd.setObjectName("e_user_pwd")
        self.label_11 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_11.setGeometry(QtCore.QRect(10, 136, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_12.setGeometry(QtCore.QRect(10, 96, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_15.setGeometry(QtCore.QRect(10, 56, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.e_lider_username = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.e_lider_username.setGeometry(QtCore.QRect(230, 166, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_lider_username.sizePolicy().hasHeightForWidth())
        self.e_lider_username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.e_lider_username.setFont(font)
        self.e_lider_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.e_lider_username.setObjectName("e_lider_username")
        self.label_13 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_13.setGeometry(QtCore.QRect(10, 211, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_16.setGeometry(QtCore.QRect(10, 171, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.e_lider_username_pwd = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.e_lider_username_pwd.setGeometry(QtCore.QRect(230, 206, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_lider_username_pwd.sizePolicy().hasHeightForWidth())
        self.e_lider_username_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.e_lider_username_pwd.setFont(font)
        self.e_lider_username_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.e_lider_username_pwd.setObjectName("e_lider_username_pwd")
        self.label_33 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_33.setGeometry(QtCore.QRect(10, 242, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.e_hosts = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.e_hosts.setGeometry(QtCore.QRect(230, 241, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_hosts.sizePolicy().hasHeightForWidth())
        self.e_hosts.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.e_hosts.setFont(font)
        self.e_hosts.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.e_hosts.setObjectName("e_hosts")
        self.ldap_server = QtWidgets.QLineEdit(self.ejabberd_server_conf)
        self.ldap_server.setGeometry(QtCore.QRect(230, 280, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ldap_server.sizePolicy().hasHeightForWidth())
        self.ldap_server.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ldap_server.setFont(font)
        self.ldap_server.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ldap_server.setObjectName("ldap_server")
        self.label_34 = QtWidgets.QLabel(self.ejabberd_server_conf)
        self.label_34.setGeometry(QtCore.QRect(10, 281, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.ejabberd_install = QtWidgets.QCheckBox(self.ejabberd_server_conf)
        self.ejabberd_install.setGeometry(QtCore.QRect(10, 25, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ejabberd_install.setFont(font)
        self.ejabberd_install.setObjectName("ejabberd_install")
        Installer.addPage(self.lider_conf_page)
        self.watch_log_page = QtWidgets.QWizardPage()
        self.watch_log_page.setObjectName("watch_log_page")
        self.lider_text = QtWidgets.QTextEdit(self.watch_log_page)
        self.lider_text.setGeometry(QtCore.QRect(63, 53, 811, 721))
        self.lider_text.setOverwriteMode(True)
        self.lider_text.setObjectName("lider_text")
        self.next_install_button = QtWidgets.QPushButton(self.watch_log_page)
        self.next_install_button.setGeometry(QtCore.QRect(930, 60, 83, 24))
        self.next_install_button.setStyleSheet("")
        self.next_install_button.setObjectName("next_install_button")
        Installer.addPage(self.watch_log_page)

        self.retranslateUi(Installer)
        QtCore.QMetaObject.connectSlotsByName(Installer)

    def retranslateUi(self, Installer):
        _translate = QtCore.QCoreApplication.translate
        Installer.setWindowTitle(_translate("Installer", "Lider Ahenk Kolay Kurulum Uygulaması"))
        self.connect_server_conf.setTitle(_translate("Installer", "Bağlantı Ayarları"))
        self.label_25.setText(_translate("Installer", "Bileşenler Nereye Kurulsun"))
        self.location.setItemText(0, _translate("Installer", "Yerel Makineye Kur"))
        self.location.setItemText(1, _translate("Installer", "Uzak Makineye Kur"))
        self.label_28.setText(_translate("Installer", "Kullanıcı Parolası"))
        self.label_27.setText(_translate("Installer", "Sunucu Bilgisi"))
        self.username.setText(_translate("Installer", "tcolak"))
        self.user_password.setText(_translate("Installer", "secret"))
        self.button_ssh_control.setText(_translate("Installer", "Bağlantı Kontrol"))
        self.server_host.setText(_translate("Installer", "192.168.56.1"))
        self.label_14.setText(_translate("Installer", "Kullanıcı Adı"))
        self.textBrowser_43.setHtml(_translate("Installer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Lider Sunucu Konfigürasyonu</span></p></body></html>"))
        self.ldap_server_conf.setTitle(_translate("Installer", "LDAP Sunucu Ayarları"))
        self.l_base_dn.setText(_translate("Installer", "liderahenk.org"))
        self.l_admin_pwd.setText(_translate("Installer", "secret"))
        self.ldap_admin_cn.setText(_translate("Installer", "admin"))
        self.label_2.setText(_translate("Installer", "LDAP İçin İşlem Seçiniz"))
        self.label_3.setText(_translate("Installer", "LDAP Admin Kullanıcı Adı"))
        self.label_4.setText(_translate("Installer", "LDAP Admin Parolası"))
        self.label_5.setText(_translate("Installer", "LDAP Base DN"))
        self.lider_console_user.setText(_translate("Installer", "lider_console"))
        self.l_org_name.setText(_translate("Installer", "liderahenk"))
        self.label_6.setText(_translate("Installer", "LDAP Config Parolası"))
        self.label_7.setText(_translate("Installer", "LDAP Config Kullanıcı Adı"))
        self.l_config_admin_dn.setText(_translate("Installer", "cn=admin,cn=config"))
        self.label_8.setText(_translate("Installer", "Lider Arayüz Kullanıcı Adı"))
        self.label_9.setText(_translate("Installer", "LDAP Organizasyon Adı"))
        self.l_config_pwd.setText(_translate("Installer", "secret"))
        self.label_10.setText(_translate("Installer", "Lider Arayüz Kullanıcı Parolası"))
        self.lider_console_user_pwd.setText(_translate("Installer", "secret"))
        self.ldap_status.setItemText(0, _translate("Installer", "OpenLDAP Kur"))
        self.ldap_status.setItemText(1, _translate("Installer", "OpenLDAP Güncelle"))
        self.ldap_install.setText(_translate("Installer", "LDAP Kur"))
        self.database_server_conf.setTitle(_translate("Installer", "Veritabanı Sunucu Ayarları"))
        self.label_20.setText(_translate("Installer", "Veritabanı Kullanıcı Parolası"))
        self.db_username.setText(_translate("Installer", "root"))
        self.label_19.setText(_translate("Installer", "Veritabanı Adı"))
        self.db_password.setText(_translate("Installer", "secret"))
        self.label_18.setText(_translate("Installer", "Veritabanı Kullanıcı Adı"))
        self.label_17.setText(_translate("Installer", "Veritabanı Sunucu Adresi"))
        self.db_server.setText(_translate("Installer", "127.0.0.1"))
        self.db_name.setText(_translate("Installer", "liderdb"))
        self.db_install.setText(_translate("Installer", "Veritabanı Kur"))
        self.file_server_conf.setTitle(_translate("Installer", "Dosya Sunucu Ayarları"))
        self.fs_username.setText(_translate("Installer", "lider"))
        self.fs_plugin_path.setText(_translate("Installer", "/usr/share/lider-server"))
        self.fs_username_pwd.setText(_translate("Installer", "secret"))
        self.label_21.setText(_translate("Installer", "Eklenti Yolu"))
        self.label_23.setText(_translate("Installer", "Kullanıcı Adı"))
        self.label_24.setText(_translate("Installer", "Kullanıcı Parolası"))
        self.label_22.setText(_translate("Installer", "Ahenk Dosyaları Yolu"))
        self.label_26.setText(_translate("Installer", "Kullanıcı Sözleşmesi Yolu"))
        self.fs_agent_files_path.setText(_translate("Installer", "/usr/share/lider-server"))
        self.fs_agreement_path.setText(_translate("Installer", "/usr/share/lider-server"))
        self.label_32.setText(_translate("Installer", "Dosya Sunucu Adresi"))
        self.file_server.setText(_translate("Installer", "192.168.56.1"))
        self.lider_install.setText(_translate("Installer", "Lider Kur"))
        self.save_button.setText(_translate("Installer", "Kaydet"))
        self.ejabberd_server_conf.setTitle(_translate("Installer", "Ejabberd Sunucu Ayarları"))
        self.e_service_name.setText(_translate("Installer", "im.liderahenk.org"))
        self.e_username.setText(_translate("Installer", "admin"))
        self.e_user_pwd.setText(_translate("Installer", "secret"))
        self.label_11.setText(_translate("Installer", "Admin Parolası"))
        self.label_12.setText(_translate("Installer", "Admin Kullanıcı Adı"))
        self.label_15.setText(_translate("Installer", "Servis Adı"))
        self.e_lider_username.setText(_translate("Installer", "lider_sunucu"))
        self.label_13.setText(_translate("Installer", "Lider Kullanıcı Parolası"))
        self.label_16.setText(_translate("Installer", "Lider Kullanıcı Adı"))
        self.e_lider_username_pwd.setText(_translate("Installer", "secret"))
        self.label_33.setText(_translate("Installer", "Sunucu Adresi"))
        self.e_hosts.setText(_translate("Installer", "192.168.56.1"))
        self.ldap_server.setText(_translate("Installer", "192.168.56.1"))
        self.label_34.setText(_translate("Installer", "LDAP Adresi"))
        self.ejabberd_install.setText(_translate("Installer", "Ejabberd Kur"))
        self.next_install_button.setText(_translate("Installer", "Kur"))

