#!/bin/bash

CNAME="#CNAME"
BASEDN="#BASEDN"
BASECN="#BASECN"
ORGANIZATION="#ORGANIZATION"

ADMINCN="#ADMINCN"
ADMINPASSWD="#ADMINPASSWD"
CNCONFIGADMINDN="#CNCONFIGADMINDN"
CNCONFIGADMINPASSWD="#CNCONFIGADMINPASSWD"
LIDERAHENK_SCHEMA_PATH="/tmp/liderahenk.ldif"

LIDERCONSOLEUSER="#LIDERCONSOLEUSER"
LIDERCONSOLEPWD="#LIDERCONSOLEPWD"
ADMINDN="$ADMINCN,$BASEDN"

systemctl restart slapd.service

# password for cn=admin,cn=config
NEW_PASSWD=$(slappasswd -h {SSHA} -s $CNCONFIGADMINPASSWD)
echo $NEW_PASSWD

# Set password for cn=admin,cn=config
ldapmodify -Y EXTERNAL -H ldapi:/// << EOL
dn: olcDatabase={0}config,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: $NEW_PASSWD

dn: cn=config
replace: olcAuthzRegexp
olcAuthzRegexp: {0}uid=([^,]*),cn=[^,]*,cn=auth  ldap:///$BASEDN??sub?(uid=\$1)
-
replace: olcSizeLimit
olcSizeLimit: 10000
EOL


# add liderahenk.ldif file to ldap
ldapadd -x -D "$CNCONFIGADMINDN" -f $LIDERAHENK_SCHEMA_PATH -w $CNCONFIGADMINPASSWD

ldapadd -x -D "$ADMINDN" -w $ADMINPASSWD << EOL
dn: cn=liderAhenkConfig,$BASEDN
changetype: add
objectClass: pardusLiderAhenkConfig
liderServiceAddress: http://lider.$CNAME:8181
cn: liderAhenkConfig

dn: cn=$LIDERCONSOLEUSER,$BASEDN
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: pardusAccount
objectClass: pardusLider
objectClass: person
objectClass: top
cn: $LIDERCONSOLEUSER
sn: $LIDERCONSOLEUSER
uid: $LIDERCONSOLEUSER
userPassword: $LIDERCONSOLEPWD
liderPrivilege: [REPORT:ALL]
liderPrivilege: [TASK:$BASEDN:ALL]

dn: ou=Ahenkler,$BASEDN
objectClass: organizationalUnit
objectClass: top
ou: Ahenkler
description: pardusDeviceGroup

dn: cn=adminGroups,$BASEDN
objectClass: groupOfNames
objectClass: top
member: $ADMINDN
cn: adminGroups
description: User group with ldap write permission
EOL

# User group with ldap write permission
ldapmodify -Y EXTERNAL -H ldapi:/// << EOL
dn: olcDatabase={1}mdb,cn=config
changetype: modify
add: olcAccess
olcAccess: {1}to dn.subtree="$BASEDN" by group.exact="cn=adminGroups,$BASEDN" write by * read
EOL

systemctl restart slapd.service